export const presetPhrases = [
  "Flight BC767 is now boarding",
  "Flight DAN119 ahs been delayed",
  "This is the final call for flight TM121 to Istanbul",
];

export const presetLanguageSettings = [
  {
    locale: {
      value: "en-US",
      locale: "en-US",
      displayName: "English (United States)",
      label: "English (United States)",
      language: "en",
    },
    voice: {
      voiceShortName: "en-US-JennyNeural",
      displayName: "Jenny (Neural)",
      voiceType: "OnlineNeural",
      isStyleDegreeSupported: false,
      styles: [
        { styleName: "assistant", displayName: "Assistant" },
        { styleName: "chat", displayName: "Chat" },
        { styleName: "customerservice", displayName: "Customer Service" },
        { styleName: "newscast", displayName: "News Cast" },
      ],
      roles: [],
      pitchOptions: ["x-low", "low", "medium", "high", "x-high", "default"],
      rateOptions: ["x-slow", "slow", "medium", "fast", "x-fast", "default"],
      value: "en-US-JennyNeural",
      label: "Jenny (Neural)",
      adjustments: {
        pitch: 5,
        rate: 100,
        style: {
          styleName: "assistant",
          displayName: "Assistant",
          label: "Assistant",
          value: "assistant",
        },
      },
    },
  },
  {
    locale: {
      locale: "fr-FR",
      value: "fr-FR",
      displayName: "French (France)",
      label: "French (France)",
      language: "fr",
    },
    voice: {
      voiceShortName: "fr-FR-DeniseNeural",
      displayName: "Denise (Neural)",
      voiceType: "OnlineNeural",
      isStyleDegreeSupported: false,
      styles: [],
      roles: [],
      pitchOptions: ["x-low", "low", "medium", "high", "x-high", "default"],
      rateOptions: ["x-slow", "slow", "medium", "fast", "x-fast", "default"],
      value: "fr-FR-DeniseNeural",
      label: "Denise (Neural)",
      adjustments: { pitch: 5, rate: 100 },
    },
  },
  {
    locale: {
      locale: "es-MX",
      value: "es-MX",
      displayName: "Spanish (Mexico)",
      label: "Spanish (Mexico)",
      language: "es",
    },
    voice: {
      voiceShortName: "es-MX-DaliaNeural",
      displayName: "Dalia (Neural)",
      voiceType: "OnlineNeural",
      isStyleDegreeSupported: false,
      styles: [],
      roles: [],
      pitchOptions: ["x-low", "low", "medium", "high", "x-high", "default"],
      rateOptions: ["x-slow", "slow", "medium", "fast", "x-fast", "default"],
      value: "es-MX-DaliaNeural",
      label: "Dalia (Neural)",
      adjustments: { pitch: 5, rate: 100 },
    },
  },
  {
    locale: {
      locale: "da-DK",
      value: "da-DK",
      displayName: "Danish (Denmark)",
      label: "Danish (Denmark)",
      language: "da",
    },
    voice: {
      voiceShortName: "da-DK-ChristelNeural",
      displayName: "Christel (Neural)",
      voiceType: "OnlineNeural",
      isStyleDegreeSupported: false,
      styles: [],
      roles: [],
      pitchOptions: ["x-low", "low", "medium", "high", "x-high", "default"],
      rateOptions: ["x-slow", "slow", "medium", "fast", "x-fast", "default"],
      value: "da-DK-ChristelNeural",
      label: "Christel (Neural)",
      adjustments: { pitch: 5, rate: 100 },
    },
  },
  {
    locale: {
      locale: "ja-JP",
      value: "ja-JP",
      displayName: "Japanese (Japan)",
      label: "Japanese (Japan)",
      language: "ja",
    },
    voice: {
      voiceShortName: "ja-JP-NanamiNeural",
      displayName: "Nanami (Neural)",
      voiceType: "OnlineNeural",
      isStyleDegreeSupported: false,
      styles: [],
      roles: [],
      pitchOptions: ["x-low", "low", "medium", "high", "x-high", "default"],
      rateOptions: ["x-slow", "slow", "medium", "fast", "x-fast", "default"],
      value: "ja-JP-NanamiNeural",
      label: "Nanami (Neural)",
      adjustments: { pitch: 5, rate: 100 },
    },
  },
  {
    locale: {
      locale: "hi-IN",
      value: "hi-IN",
      displayName: "Hindi (India)",
      label: "Hindi (India)",
      language: "hi",
    },
    voice: {
      voiceShortName: "hi-IN-MadhurNeural",
      displayName: "Madhur (Neural)",
      voiceType: "OnlineNeural",
      isStyleDegreeSupported: false,
      styles: [],
      roles: [],
      pitchOptions: ["x-low", "low", "medium", "high", "x-high", "default"],
      rateOptions: ["x-slow", "slow", "medium", "fast", "x-fast", "default"],
      value: "hi-IN-MadhurNeural",
      label: "Madhur (Neural)",
      adjustments: { pitch: 5, rate: 100 },
    },
  },
];
